name: release
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - id: meta
        run: |
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "repo_lower=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # on force des tags en minuscules, indépendants du nom du repo
          tags: |
            ghcr.io/fredinard/abrasia-backend:latest
            ghcr.io/fredinard/abrasia-backend:${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha }}
